### ISSUE TITLE
BUG: SamQuantileMLP predict_ahead doesn't support Sequence

### ISSUE THREAD

**Issue by sbuergers** [RoyalHaskoningDHV/sam#17]
The type-hint for predict_ahead in SamQuantileMLP is
predict_ahead: Union[int, Sequence[int]] = 1,

But the parent BaseTimeseriesRegressor only supports List:
predict_ahead: Union[int, List[int]] = 1,

```python
>>> predict_ahead = (0,)
>>> isinstance(predict_ahead, Sequence)
True
>>> model = SamQuantileMLP(predict_ahead=predict_ahead)
>>> model.predict_ahead
[(0,)]
>>> model.validate_predict_ahead()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\921266\source\repos\sam\sam\models\base_model.py", line 141, in validate_predict_ahead
    if not all([p >= 0 for p in self.predict_ahead]):
  File "C:\Users\921266\source\repos\sam\sam\models\base_model.py", line 141, in <listcomp>
    if not all([p >= 0 for p in self.predict_ahead]):
TypeError: '>=' not supported between instances of 'tuple' and 'int'
This is caused by the following line:
self.predict_ahead = (
    predict_ahead if isinstance(predict_ahead, List) else [predict_ahead]
)
```

**Comment by abontsema** [comment]
This is no longer relevant after major changes in #42 . `predict_ahead` should now always be a tuple.
